<?php

return [
    'presets' => [
        'default' => [
            'label' => 'Default (Brand)',
            'primary_color' => '#E31E24',
            'secondary_color' => '#0A0A0A',
            'accent_color' => '#141414',
            'ticker_bg_color' => '#E31E24',
            'decoration' => 'none',
            'hero_overlay' => 'default',
        ],
        'diwali' => [
            'label' => 'Diwali',
            'primary_color' => '#FF6B00',
            'secondary_color' => '#1A0A00',
            'accent_color' => '#FFD700',
            'ticker_bg_color' => '#B45309',
            'decoration' => 'sparkles',
            'hero_overlay' => 'warm',
        ],
        'holi' => [
            'label' => 'Holi',
            'primary_color' => '#EC4899',
            'secondary_color' => '#312E81',
            'accent_color' => '#22D3EE',
            'ticker_bg_color' => '#DB2777',
            'decoration' => 'confetti',
            'hero_overlay' => 'colorful',
        ],
        'christmas' => [
            'label' => 'Christmas',
            'primary_color' => '#DC2626',
            'secondary_color' => '#14532D',
            'accent_color' => '#FBBF24',
            'ticker_bg_color' => '#166534',
            'decoration' => 'snow',
            'hero_overlay' => 'festive',
        ],
        'republic_day' => [
            'label' => 'Republic Day',
            'primary_color' => '#FF9933',
            'secondary_color' => '#138808',
            'accent_color' => '#000080',
            'ticker_bg_color' => '#FF9933',
            'decoration' => 'none',
            'hero_overlay' => 'patriotic',
        ],
        'independence_day' => [
            'label' => 'Independence Day',
            'primary_color' => '#FF9933',
            'secondary_color' => '#138808',
            'accent_color' => '#FFFFFF',
            'ticker_bg_color' => '#138808',
            'decoration' => 'none',
            'hero_overlay' => 'patriotic',
        ],
        'new_year' => [
            'label' => 'New Year',
            'primary_color' => '#6366F1',
            'secondary_color' => '#0F172A',
            'accent_color' => '#FBBF24',
            'ticker_bg_color' => '#4F46E5',
            'decoration' => 'sparkles',
            'hero_overlay' => 'night',
        ],
        'sale' => [
            'label' => 'Mega Sale',
            'primary_color' => '#E31E24',
            'secondary_color' => '#0A0A0A',
            'accent_color' => '#FBBF24',
            'ticker_bg_color' => '#E31E24',
            'decoration' => 'none',
            'hero_overlay' => 'default',
        ],
    ],

    'decorations' => [
        'none' => 'None',
        'confetti' => 'Confetti',
        'sparkles' => 'Sparkles',
        'snow' => 'Snow',
    ],

    'hero_overlays' => [
        'default' => 'Default dark gradient',
        'warm' => 'Warm golden glow',
        'colorful' => 'Colorful festival',
        'festive' => 'Festive green/red',
        'patriotic' => 'Tricolor tint',
        'night' => 'Night sky',
    ],
];
